name: Branch Naming

on:
  create:

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"

          # Define the expected pattern
          PATTERN="^(feature|fix|hotfix|chore|docs|test|release)\/([A-Za-z0-9._-]+)$"

          if [[ ! $BRANCH_NAME =~ $PATTERN ]]; then
            echo "::error::Branch name '$BRANCH_NAME' does not follow the convention: <type>/<description>"
            echo "Valid types are: feature, fix, hotfix, chore, docs, test, release"
            exit 1
          fi
